package org.cyk.system.school.model;

public interface SchoolConstant {

	String LEVEL_GROUP_KINDERGARTEN = "KINDERGARTEN";
	String LEVEL_GROUP_PRIMARY = "PRIMARY";
	String LEVEL_GROUP_SECONDARY = "SECONDARY";
	
	String REPORT_CYK_GLOBAL_RANKABLE = "CYK_GLOBAL_RANKABLE";
	
	String INTANGIBLE_PRODUCT_TUITION = "TUITION";
	
	/**/
	
	String UI_TAB_BROADSHEET_ID = "school.broadsheet";
	
	String REPORT_STUDENT_REGISTRATION_CERTIFICATE = "STUDENT_REGISTRATION_CERTIFICATE";
	String REPORT_STUDENT_TUITION_CERTIFICATE = "STUDENT_TUTION_CERTIFICATE";
	String REPORT_STUDENT_CLASSROOM_SESSION_DIVISION_SHEET = "STUDENT_CLASSROOM_SESSION_DIVISION_SHEET";

}
